---
- name: "Include Ansible"
  ansible.builtin.include_role:
    name: "ansible"
- name: Install Molecule
  ansible.builtin.pip:
    name:
      - molecule==5.0.0
      - molecule-plugins[vagrant]
      - python-vagrant
      - rich
    virtualenv: '{{ python_venv_directory }}'
  when: enable_develop_molecule
