---
- name: "Include Python"
  ansible.builtin.include_role:
    name: "python"
- name: Ensure that Ansible is installed
  ansible.builtin.pip:
    name:
      - ansible-core
    virtualenv: '{{ python_venv_directory }}'
